// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Senhas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108121840_AddAuditoriaLogins")]
    partial class AddAuditoriaLogins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Senhas.Models.Entities.AuditoriaLogins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Navegador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditoriaLogins");
                });

            modelBuilder.Entity("Senhas.Models.Entities.Guiche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guiches");
                });

            modelBuilder.Entity("Senhas.Models.Entities.Senha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataChamada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GuicheId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoSenhaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuicheId");

                    b.HasIndex("TipoSenhaId");

                    b.ToTable("Senhas");
                });

            modelBuilder.Entity("Senhas.Models.Entities.TipoSenha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TiposSenha");
                });

            modelBuilder.Entity("Senhas.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Confirmado")
                        .HasColumnType("boolean");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenConfirmacao")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Senhas.Models.Entities.UsuarioGuiche", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("GuicheId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "GuicheId");

                    b.HasIndex("GuicheId");

                    b.ToTable("UsuariosGuiches");
                });

            modelBuilder.Entity("Senhas.Models.Entities.Senha", b =>
                {
                    b.HasOne("Senhas.Models.Entities.Guiche", "Guiche")
                        .WithMany()
                        .HasForeignKey("GuicheId");

                    b.HasOne("Senhas.Models.Entities.TipoSenha", "TipoSenha")
                        .WithMany()
                        .HasForeignKey("TipoSenhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guiche");

                    b.Navigation("TipoSenha");
                });

            modelBuilder.Entity("Senhas.Models.Entities.UsuarioGuiche", b =>
                {
                    b.HasOne("Senhas.Models.Entities.Guiche", "Guiche")
                        .WithMany("UsuarioGuiches")
                        .HasForeignKey("GuicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Senhas.Models.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioGuiches")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guiche");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Senhas.Models.Entities.Guiche", b =>
                {
                    b.Navigation("UsuarioGuiches");
                });

            modelBuilder.Entity("Senhas.Models.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioGuiches");
                });
#pragma warning restore 612, 618
        }
    }
}
